"""add archived_at to students

Revision ID: cd86d8f2f501
Revises: 7d82b71d54bc
Create Date: 2026-07-31 12:32:53.717196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd86d8f2f501'
down_revision: Union[str, Sequence[str], None] = '7d82b71d54bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_students_archived_at'), 'students', ['archived_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_archived_at'), table_name='students')
    op.drop_column('students', 'archived_at')
    # ### end Alembic commands ###
